#path to directory of zarrs converted from slides
image_dir: test_data/image_zarr

#path to directory of zarrs storing the ViT feature representstion
feature_dir: test_data/results

#path to directory of zarrs storing ROI masks of the slides
roi_mask_dir: test_data/rois

#label indicating which ROI mask should be used to determine the regions to scan 
roi_type: "tissue"

#minimum required area in number of pixels for an object to be scanned 
roi_min_area: 100000

#maximum permitted area in number of pixels for an object to be scanned (0 indicates no max)
roi_max_area: 0

#numper of channels output by the headless ViT
vit_model_channels: 1280

#size of step between scan patches
scan_step: 28

#number of patches per batch
batch_size: 10

#number of batches to be handeled by each scan process
scan_group_size: 5

#number of times to downsample befor scanning (scan patch will be 1/2^(scan_ds) the resolution of the initial image)
scan_ds: 0

#number of times downssampled before identifying the regions to be scanned
roi_mask_ds: 0

#flag indicating if the whole image should be scanned ignoring ROIs
complete_scan: False

#flag indicating if existing ROIs should be recomputed
compute_rois: False

#what model to use for identifying ROIs if not precomputed and compute_rois
roi_identifier_model: ChannelMeanThresh

#Threshold for simple ROI detection models pixels with higer intensity will be considered background
roi_thresh: 0.8

#size of input to the model
patch_size: 224

#path to .pth file with alternate weights
model_checpoint: ""

#target torch device, must be one of ['auto', 'cuda', 'cpu']
device: auto

#create a mask of which patches have been scanned (useful for sanity checking the scan)
#creates an ineficent zarr and shoulb be set to false outside of test/debug runs
scan_mask : true

